"use client";
import {useEffect,useMemo,useState} from "react";
import {buildStrategyPaths,diagnosisQuestions,getState,resolveDiagnosis,type AnswerValue} from "../lib/zhidao-model";

type Screen="home"|"diagnose"|"map"|"system"|"history";
type RecordItem={date:string;hex:string,target:string,mode:string,progress:number};
const modes=[{name:"自动驾驶",desc:"系统在每个节点自动重新寻优"},{name:"半自动",desc:"目标变化时先请你确认"},{name:"手动锁定",desc:"终点不变，只重算路径"},{name:"静默陪伴",desc:"不主动打扰，打开时再更新"}];

function BrandMark({className=""}:{className?:string}){return <svg className={`brand-mark ${className}`} viewBox="0 0 120 120" aria-hidden="true"><g fill="none" strokeLinecap="butt"><path className="mark-deep mark-wide" d="M28 0 L54 26 M66 38 L82 54 M94 66 L120 92"/><path className="mark-soft mark-thin" d="M0 28 L26 54 M38 66 L54 82 M66 94 L92 120"/><path className="mark-deep mark-wide" d="M0 92 L26 66 M38 54 L54 38 M66 26 L92 0"/><path className="mark-soft mark-thin" d="M28 120 L54 94 M66 82 L82 66 M94 54 L120 28"/></g><circle className="mark-dot" cx="60" cy="60" r="2.8"/></svg>}
function Trigram({code}:{code:string}){return <span className="trigram" aria-label={`卦象编码 ${code}`}>{code.split("").map((v,i)=><i className={v==="1"?"yang":"yin"} key={i}/>)}</span>}
const guaNames=["坤","剥","比","观","豫","晋","萃","否","谦","艮","蹇","渐","小过","旅","咸","遁","师","蒙","坎","涣","解","未济","困","讼","升","蛊","井","巽","恒","鼎","大过","姤","复","颐","屯","益","震","噬嗑","随","无妄","明夷","贲","既济","家人","丰","离","革","同人","临","损","节","中孚","归妹","睽","兑","履","泰","大畜","需","小畜","大壮","大有","夬","乾"];
function makeChangeScene(){const fromCode=Math.floor(Math.random()*64),moving=Math.floor(Math.random()*6),toCode=fromCode^(1<<moving),toLines=Array.from({length:6},(_,i)=>(toCode>>i)&1);return{from:guaNames[fromCode],to:guaNames[toCode],moving,toLines}}
function DynamicChange(){const[scene,setScene]=useState({from:"乾",to:"履",moving:2,toLines:[1,1,0,1,1,1]});useEffect(()=>{setScene(makeChangeScene());const timer=setInterval(()=>setScene(makeChangeScene()),4200);return()=>clearInterval(timer)},[]);return <div className="change-stage" aria-label="动态变卦演示"><div className="change-meta"><span>动态变卦 · 随机一爻</span><b>{scene.from}之{scene.to}</b><small>一次变卦，多种可能</small></div><div className="six-lines">{scene.toLines.map((v,i)=><i className={`${v?"yang":"yin"} ${i===scene.moving?"moving":""}`} key={`${scene.from}-${scene.to}-${i}`}><span/><span/></i>)}</div><em className="change-word change">变易</em><em className="change-word constant">不易</em><em className="change-word simple">简易</em><div className="change-caption"><span>本卦 · {scene.from}</span><i>第 {scene.moving+1} 爻变</i><span>之卦 · {scene.to}</span></div></div>}

export default function Home(){
 const[screen,setScreen]=useState<Screen>("home"),[step,setStep]=useState(0),[answers,setAnswers]=useState<(AnswerValue|undefined)[]>([]),[path,setPath]=useState(0),[mode,setMode]=useState(1),[records,setRecords]=useState<RecordItem[]>([]),[saved,setSaved]=useState(false);
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem("linxia-fskn-records")||"[]"))}catch{}},[]);
 const hex=useMemo(()=>resolveDiagnosis(answers),[answers]);
 const inertia=getState(hex.inertiaId);
 const targetPaths=useMemo(()=>buildStrategyPaths(hex),[hex]);
 const chosen=targetPaths[path]||targetPaths[0];
 const nav=(s:Screen)=>{setScreen(s);scrollTo(0,0)};
 function start(){setStep(0);setAnswers([]);setPath(0);setSaved(false);nav("diagnose")}
 function answer(value:AnswerValue){let next=[...answers];next[step]=value;setAnswers(next);if(step<2)setStep(step+1);else nav("map")}
 function save(){if(saved)return;let next=[{date:new Date().toLocaleDateString("zh-CN"),hex:hex.name+" · "+hex.title,target:chosen.target+" · "+chosen.name,mode:modes[mode].name,progress:33},...records].slice(0,12);setRecords(next);setSaved(true);localStorage.setItem("linxia-fskn-records",JSON.stringify(next))}
 return <main>
  <header className="top"><button className="brand" onClick={()=>nav("home")}><BrandMark className="brand-symbol"/><span><b>知道 · 管理</b><small>林下问路｜网罟天下，以佃以渔</small></span></button><nav><button onClick={start}>处境诊断</button><button onClick={()=>nav("system")}>方法体系</button><button onClick={()=>nav("history")}>演化记录 <i>{records.length}</i></button></nav></header>
  {screen!=="home"&&<div className="subnav"><button onClick={()=>nav("home")}>← 林下入口</button><ol>{["知境","见势","择路","迭代"].map((x,i)=><li className={(screen==="diagnose"&&i<=0)||(screen==="map"&&i<=2)||(screen==="history")?"on":""} key={x}><span>0{i+1}</span>{x}</li>)}</ol><b>FSKN / V6.0</b></div>}

  {screen==="home"&&<><section className="hero"><div className="hero-left"><div className="hero-brand"><BrandMark className="hero-symbol"/><div><b>林下问路</b><small>ZHIDAO MANAGEMENT</small></div></div><p className="eyebrow">林下问路 · 组织处境诊断与动态推演</p><h1>知境，<br/><em>而后知道。</em></h1><p className="lead">以关系结构为镜，以管理实践为用。<br/>看见现在在哪里，不改变会去哪里，以及下一爻可以怎样动。</p><div className="actions"><button className="primary" onClick={start}>开始三问诊断 <span>↗</span></button><button className="link" onClick={()=>nav("system")}>先了解方法体系</button></div><div className="promise"><span>01 三问知境</span><span>02 动态变卦</span><span>03 三路寻优</span></div></div><DynamicChange/></section>
  <section className="triple"><div className="section-title"><p className="eyebrow">三卦路径沙盘</p><h2>不是一条静态路线，<br/>而是持续修正的航向。</h2></div>{[["现状之卦","极简自拍","把三次选择编码成当下处境"],["惯性之卦","默认趋势","推演非干预状态下的自然滑向"],["目标之卦","期望终点","比较代价，选择当前更好的归宿"]].map((v,i)=><article key={v[0]}><span>0{i+1}</span><h3>{v[0]}</h3><b>{v[1]}</b><p>{v[2]}</p><i/></article>)}</section>
  <section className="engine"><aside><p className="eyebrow">四层策略引擎</p><h2>古典意象在表，<br/>离散结构在里。</h2><p>从五行的关系空间，到八卦的瞬时处境、六十四卦的情境议题，再到易林的演化建议。用户不必理解数学，也能获得可解释的判断。</p><button className="light" onClick={()=>nav("system")}>查看完整映射 →</button></aside><div>{[["0","五行","管理的基本关系"],["1","八卦","八种基础处境"],["2","六十四卦","六十四种情境议题"],["3","易林","变化中的操作线索"]].map(v=><article key={v[0]}><small>LEVEL {v[0]}</small><b>{v[1]}</b><p>{v[2]}</p></article>)}</div></section></>}

  {screen==="diagnose"&&<section className="diagnose"><aside><p className="eyebrow">三变即三问</p><h1>不问你是谁，<br/>只问此刻发生了什么。</h1><p>三问分别辨认三种正交的二相管理行为。每一次选择都会写入 S₈ 状态表，生成可解释的现状之卦。</p><div className="progress"><span style={{width:`${(step+1)/3*100}%`}}/></div><small>{step+1} / 3</small></aside><div className="question"><p className="eyebrow">{diagnosisQuestions[step].label}</p><h2>{diagnosisQuestions[step].title}</h2><p>{diagnosisQuestions[step].note}</p><small className="axis">{diagnosisQuestions[step].axis}</small><div className="options">{diagnosisQuestions[step].options.map((x,i)=><button onClick={()=>answer(x.value)} key={x.text}><span>{String.fromCharCode(65+i)}</span><b>{x.text}</b><small>{x.evidence}</small><i>写入状态 →</i></button>)}</div>{step>0&&<button className="back" onClick={()=>setStep(step-1)}>← 返回上一问</button>}</div></section>}

  {screen==="map"&&<section className="map-page"><div className="map-head"><p className="eyebrow">三卦路径沙盘 · 本次诊断</p><span>STATE / S₈-{hex.id} / {hex.code}</span><h1>{hex.title}</h1><p>{hex.symptom}</p></div><div className="three-hex"><article className="current"><small>现状之卦 · S₈</small><div><Trigram code={hex.code}/><b>{hex.name}</b></div><h2>{hex.title}</h2><p>{hex.explanation}</p></article><i>不干预 →</i><article className="inertia"><small>惯性之卦 · 默认趋势</small><div><Trigram code={inertia.code}/><b>{inertia.name}</b></div><h2>{hex.inertiaTitle}</h2><p>{hex.warning}</p></article><i>主动选择 →</i><article className="target"><small>目标之卦 · 期望终点</small><div><Trigram code={chosen.targetCode}/><b>{chosen.target}</b></div><h2>{chosen.name}</h2><p>{chosen.desc}</p></article></div>
  <div className="path-pick"><div><p className="eyebrow">三条推荐路径 · P₄₀₉₆ 雏形</p><h2>你愿意承担哪一种改变？</h2></div><section>{targetPaths.map((p,i)=><button className={i===path?"selected":""} onClick={()=>setPath(i)} key={p.tag}><span>{p.tag}</span><div><b>{p.name}</b><small>{p.cost}</small><p>{p.desc}</p><em>{p.rationale}</em></div><i>{i===path?"已选择":"比较此路"}</i></button>)}</section></div>
  <div className="roadbook"><aside><p className="eyebrow">从 {hex.name} 到 {chosen.target}</p><h2>第一段路书</h2><p>不是一次性方案，而是抵达下一个可观测节点的行动序列。</p></aside><ol>{chosen.moves.map((x,i)=><li key={x}><span>0{i+1}</span><b>{x}</b><small>{["立即","7天","14天"][i]}</small></li>)}</ol><div className="gate"><small>收敛闸门</small><span><i/>目标锁定</span><span><i/>路径 ≤ 2 步</span><span><i/>风险信号转弱</span></div></div>
  <div className="mode"><div><p className="eyebrow">控制权在你</p><h2>下一次变化发生时，系统怎样陪你？</h2></div><div>{modes.map((m,i)=><button className={mode===i?"on":""} onClick={()=>setMode(i)} key={m.name}><b>{m.name}</b><small>{m.desc}</small></button>)}</div><button className="primary" onClick={save}>{saved?"本次路径已存档 ✓":"确认路径，进入第一次迭代"}</button></div></section>}

  {screen==="system"&&<section className="system"><div className="system-hero"><p className="eyebrow">知道管理 · 方案总览</p><h1>以关系为体，<br/>以管理实践为用。</h1><p>这套方案把组织看作一个持续变化的关系网络。它的工作不是给复杂现实贴标签，而是把当下状态、默认趋势与可选目标放进同一个可计算、可讨论的框架。</p></div><div className="axioms">{[["八卦","八种基础处境","三问先把复杂组织压缩成八种可辨认的基础姿态：乾、兑、离、震、巽、坎、艮、坤，用来回答“我现在在哪”。"],["六十四卦","八种处境的上下复合","把一个基础处境放在上层，再把另一个基础处境放在下层，形成 8 × 8 的六十四种情境议题，用来解释“为什么会这样”。"],["4096 种变卦","六十四卦之间的可达变化","任一现状卦都可能转向任一目标卦，形成 64 × 64 = 4096 条演化关系，用来比较“不变会怎样、改变往哪走、先动哪一爻”。"]].map(v=><article key={v[0]}><small>{v[0]}</small><h2>{v[1]}</h2><p>{v[2]}</p></article>)}</div><div className="math-kernel"><aside><p className="eyebrow">数学内核 · M-1.0</p><h2>从可观测三问，<br/>进入可计算演化。</h2><p>以 FSKN 数学体系为本体，把组织处境映射为离散状态空间、非交换演化和自适应控制问题。</p></aside><div>{[["状态空间","S₈","三种正交的二相管理行为，组成八种基础组织状态。"],["映射空间","M₆₄","现状状态与参照状态成对编码，形成六十四种情境议题。"],["演化空间","P₄₀₉₆","任一现状卦到任一目标卦皆为一条可比较的路径，支持代价、风险和中继点计算。"],["控制策略","π*","在惯性驱动力与干预控制力之间寻优，持续修正下一步动作。"]].map(v=><article key={v[0]}><small>{v[0]}</small><b>{v[1]}</b><p>{v[2]}</p></article>)}</div></div><div className="system-map"><aside><p className="eyebrow">产品闭环</p><h2>诊断不是终点，<br/>而是进入深度内容与持续问答的入口。</h2></aside><div>{[["诊断","我现在在哪","三问 → 八种处境"],["议题","为什么会这样","六十四种情境 · 七层阅读"],["问答","下一步怎么走","三锚点 · 200字行动指令"],["迭代","目标还对不对","内层修路 · 外层换靶"]].map((v,i)=><article key={v[0]}><span>0{i+1}</span><b>{v[0]}</b><h3>{v[1]}</h3><p>{v[2]}</p></article>)}</div></div><div className="principles"><p className="eyebrow">三重承诺</p><div><article><b>可解释</b><p>每一个判断都能回到三问、三卦与路径代价。</p></article><article><b>可选择</b><p>系统给出多条路线，目标与陪伴模式由用户决定。</p></article><article><b>可更新</b><p>变化后重新计算，旧答案不会永久定义组织。</p></article></div></div><button className="primary center" onClick={start}>从三问进入系统 <span>↗</span></button></section>}

  {screen==="history"&&<section className="history"><div className="section-title"><p className="eyebrow">演化记录 · 仅保存在此设备</p><h1>每次变卦，<br/>都是重新出发。</h1><p>这里记录的是判断如何更新，不是一个固定不变的组织画像。</p></div>{records.length?<div className="records">{records.map((r,i)=><article key={i}><time>{r.date}</time><div><small>本卦</small><b>{r.hex}</b></div><span>→</span><div><small>目标之卦</small><b>{r.target}</b></div><div className="record-progress"><i><em style={{width:`${r.progress}%`}}/></i><small>第 1 / 3 个中继节点 · {r.mode}</small></div></article>)}</div>:<div className="empty"><BrandMark className="empty-symbol"/><h2>尚未开始第一次演化</h2><p>完成三问并选择一条目标路径后，本次判断会留在这里。</p><button className="primary" onClick={start}>开始三问诊断</button></div>}</section>}
  <footer><div><BrandMark className="footer-symbol"/><span><b>知道 · 管理</b><small>林下问路</small></span></div><p>网罟天下，以佃以渔</p><span>知境，而后知道。</span></footer>
 </main>
}
